version: "3.8"

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-backend_challenge_development}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_net

  # Servidor Rails (tu app)
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-backend_challenge_development}
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - backend_net
    tty: true
    stdin_open: true

volumes:
  pg_data:

networks:
  backend_net:
    driver: bridge